#!/usr/bin/env bash
#
# Interactive .env generator for Astraccounts.
#
# Asks a few questions (most importantly the domain whose mail DNS you control)
# and writes a usable .env next to .env.example. An existing .env is backed up
# to .env.bak.<timestamp> before it is replaced.
#
# Usage: scripts/setup-env.sh [output-path]

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${1:-$ROOT/.env}"

# ask <varname> <prompt> <default>
# Reads one line, falling back to <default> on an empty answer.
ask() {
    local __var="$1" __prompt="$2" __default="${3-}" __answer
    if [ -n "$__default" ]; then
        read -r -p "$__prompt [$__default]: " __answer
    else
        read -r -p "$__prompt: " __answer
    fi
    printf -v "$__var" '%s' "${__answer:-$__default}"
}

# ask_required <varname> <prompt> — re-prompts until a non-empty answer.
ask_required() {
    local __var="$1" __prompt="$2" __answer=""
    while [ -z "$__answer" ]; do
        read -r -p "$__prompt: " __answer
    done
    printf -v "$__var" '%s' "$__answer"
}

# ask_yes_no <varname> <prompt> <default y|n>
ask_yes_no() {
    local __var="$1" __prompt="$2" __default="$3" __answer __hint
    if [ "$__default" = "y" ]; then __hint="Y/n"; else __hint="y/N"; fi
    read -r -p "$__prompt [$__hint]: " __answer
    __answer="${__answer:-$__default}"
    case "$__answer" in
        [Yy]*) printf -v "$__var" '%s' "true" ;;
        *)     printf -v "$__var" '%s' "false" ;;
    esac
}

# random_secret prints 64 hex characters (32 bytes).
random_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    elif [ -r /dev/urandom ]; then
        od -An -N32 -tx1 /dev/urandom | tr -d ' \n'
    else
        # Last resort: not cryptographically strong, but better than empty.
        printf '%s%s' "$(date +%s%N)" "$$" | sha256sum | cut -d' ' -f1
    fi
}

# is_domain <value> — accepts dotted names like mx.example.com.
is_domain() {
    printf '%s' "$1" | grep -Eq '^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)+$'
}

cat <<'BANNER'
Astraccounts .env generator
===========================
Press Enter to accept the [default]. Blank mail domain disables the mail server.
BANNER
echo

if [ -e "$ENV_FILE" ]; then
    backup="${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
    cp "$ENV_FILE" "$backup"
    echo "Existing .env backed up to $backup"
    echo
fi

# ── Core ─────────────────────────────────────────────────────────────────────
ask GIN_MODE "Gin mode (debug/release/test)" "debug"
ask GIN_TRUSTED_PROXIES "Trusted proxies (comma-separated IPs/CIDRs)" "127.0.0.1,::1"
ask TOKEN_VALID_SECS "Token validity (seconds)" "3600"
ask ALLOWED_PROFILE_KEY "Editable profile keys" "bio:string,secret:string:private"

# ── Mail ─────────────────────────────────────────────────────────────────────
echo
echo "Mail server (optional). Enter a blank domain to leave mail disabled."
ask MAIL_DOMAIN "Mail domain whose DNS you control" ""
MAIL_DOMAIN="$(printf '%s' "$MAIL_DOMAIN" | tr '[:upper:]' '[:lower:]')"

if [ -n "$MAIL_DOMAIN" ]; then
    while ! is_domain "$MAIL_DOMAIN"; do
        echo "'$MAIL_DOMAIN' does not look like a domain name."
        ask_required MAIL_DOMAIN "Mail domain whose DNS you control"
        MAIL_DOMAIN="$(printf '%s' "$MAIL_DOMAIN" | tr '[:upper:]' '[:lower:]')"
    done

    ask MAIL_HOSTNAME "Hostname shown in banners/Received headers" "mx.$MAIL_DOMAIN"
    ask MAIL_EXTRA_DOMAINS "Additional domains to accept mail for (optional)" ""

    ask MAIL_TLS_CERT_FILE "TLS certificate path (optional)" ""
    MAIL_TLS_KEY_FILE=""
    if [ -n "$MAIL_TLS_CERT_FILE" ]; then
        ask_required MAIL_TLS_KEY_FILE "TLS private key path"
    fi

    ask MAIL_DKIM_SELECTOR "DKIM selector (optional)" ""
    MAIL_DKIM_KEY_FILE=""
    MAIL_DKIM_DOMAIN=""
    if [ -n "$MAIL_DKIM_SELECTOR" ]; then
        ask_required MAIL_DKIM_KEY_FILE "DKIM private key path (PEM)"
        ask MAIL_DKIM_DOMAIN "DKIM signing domain" "$MAIL_DOMAIN"
    fi

    ask_yes_no MAIL_RELAY "Relay mail to external domains" "y"

    echo
    echo "If outbound port 25 is blocked (most cloud hosts), enter a smarthost."
    ask MAIL_SMARTHOST_ADDR "Smarthost host:port (optional)" ""
    MAIL_SMARTHOST_USER=""
    MAIL_SMARTHOST_PASSWORD=""
    if [ -n "$MAIL_SMARTHOST_ADDR" ]; then
        ask MAIL_SMARTHOST_USER "Smarthost username (optional)" ""
        if [ -n "$MAIL_SMARTHOST_USER" ]; then
            read -r -s -p "Smarthost password: " MAIL_SMARTHOST_PASSWORD
            echo
        fi
    fi
fi

TOKEN_SECRET="$(random_secret)"

# ── Write ────────────────────────────────────────────────────────────────────
{
    echo "# Generated by scripts/setup-env.sh on $(date '+%Y-%m-%d %H:%M:%S')"
    echo

    echo "# Gin runtime mode: debug, release, or test"
    echo "GIN_MODE=$GIN_MODE"
    echo
    echo "# Comma-separated IP addresses or CIDR ranges trusted for X-Forwarded-For."
    echo "GIN_TRUSTED_PROXIES=$GIN_TRUSTED_PROXIES"
    echo
    echo "# Seconds a login token stays valid after it was issued."
    echo "TOKEN_VALID_SECS=$TOKEN_VALID_SECS"
    echo
    echo "# HMAC secret used to sign login tokens."
    echo "TOKEN_SECRET=$TOKEN_SECRET"
    echo
    echo "# Profile keys a client may write through /api/profile/edit."
    echo "ALLOWED_PROFILE_KEY=$ALLOWED_PROFILE_KEY"
    echo

    if [ -z "$MAIL_DOMAIN" ]; then
        echo "# Mail server disabled (MAIL_DOMAIN is empty)."
        echo "MAIL_DOMAIN="
    else
        echo "# ── Mail server ──────────────────────────────────────────────────"
        echo "MAIL_DOMAIN=$MAIL_DOMAIN"
        echo "MAIL_HOSTNAME=$MAIL_HOSTNAME"
        echo "MAIL_EXTRA_DOMAINS=$MAIL_EXTRA_DOMAINS"
        echo
        echo "# Listener addresses. Defaults are the standard ports; \"off\" disables."
        echo "# MAIL_SMTP_ADDR=:25"
        echo "# MAIL_SUBMISSION_ADDR=:587"
        echo "# MAIL_SUBMISSION_TLS_ADDR=:465"
        echo "# MAIL_POP3_ADDR=:110"
        echo "# MAIL_POP3_TLS_ADDR=:995"
        echo "# MAIL_IMAP_ADDR=:143"
        echo "# MAIL_IMAP_TLS_ADDR=:993"
        echo
        echo "# Maximum message size in bytes (default 25 MB)."
        echo "MAIL_MAX_MESSAGE_BYTES=26214400"
        echo
        echo "# Allow relaying to domains this server does not own."
        echo "MAIL_RELAY=$MAIL_RELAY"
        echo
        echo "MAIL_TLS_CERT_FILE=$MAIL_TLS_CERT_FILE"
        echo "MAIL_TLS_KEY_FILE=$MAIL_TLS_KEY_FILE"
        echo
        if [ -n "$MAIL_SMARTHOST_ADDR" ]; then
            echo "MAIL_SMARTHOST_ADDR=$MAIL_SMARTHOST_ADDR"
            echo "MAIL_SMARTHOST_USER=$MAIL_SMARTHOST_USER"
            echo "MAIL_SMARTHOST_PASSWORD=$MAIL_SMARTHOST_PASSWORD"
        else
            echo "MAIL_SMARTHOST_ADDR="
        fi
        echo
        if [ -n "$MAIL_DKIM_SELECTOR" ]; then
            echo "MAIL_DKIM_DOMAIN=$MAIL_DKIM_DOMAIN"
            echo "MAIL_DKIM_SELECTOR=$MAIL_DKIM_SELECTOR"
            echo "MAIL_DKIM_KEY_FILE=$MAIL_DKIM_KEY_FILE"
        else
            echo "MAIL_DKIM_SELECTOR="
        fi
    fi
} > "$ENV_FILE"

echo
echo "Wrote $ENV_FILE"
if [ -n "$MAIL_DOMAIN" ]; then
    cat <<DNS

Suggested DNS records for $MAIL_DOMAIN:
  $MAIL_DOMAIN.            MX    10 $MAIL_HOSTNAME.
  $MAIL_HOSTNAME.          A     <this server's public IP>
  $MAIL_DOMAIN.            TXT   "v=spf1 mx -all"
  _dmarc.$MAIL_DOMAIN.     TXT   "v=DMARC1; p=quarantine"
DNS
    if [ -n "$MAIL_DKIM_SELECTOR" ]; then
        echo "  ${MAIL_DKIM_SELECTOR}._domainkey.$MAIL_DKIM_DOMAIN.  TXT  \"v=DKIM1; k=rsa; p=<public key>\""
    fi
fi
